# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

general:

jobs:
  
  validate-code:
    machine: true
    working_directory: ~/ci_app
    environment:
      # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
      # and https://developer.salesforce.com/media/salesforce-cli/manifest.json
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      - TESTLEVEL: RunSpecifiedTests 
      - TESTCLASSLIST: AccountRoleTriggerHelper_Test,DemoControllerTests,UpdateAmountOnAccountHelperTest
      - ISCONVERTCODE: true
      
    steps:
      - checkout # check out the code in the project directory
      
      - run:
          name: Download and Install SFDX CLI
          command: . buildScripts/installCLI.sh

      - run:
          name: Set HEAD in GitHub Repo
          command: |
            #set Git Username and Password
            git config user.email "kbssalesforce77@gmail.com"
            git config user.name "Bheru-sfdc"
            #git pull origin develop
            git pull origin << pipeline.git.branch >>

      - run:
          name: Get Changes For Deploy
          command: |
            #Using Ant script copy only changed files to a deployment source directory 
            ant -lib lib/  -DISCONVERTCODE=$ISCONVERTCODE -buildfile build.xml

      - run:
          name: Decrypting Server Key
          command: . buildScripts/decryptServerKey.sh
 
      - run:
          name: Authenticating org
          command: . buildScripts/loginToSandbox.sh

      - run:
          name: Deploy Code to Target Deployment Org
          command: . buildScripts/validateWithTest.sh

workflows:
  version: 2
  deploy-feature:
    jobs:
      - validate-code:
          name: deploy-feature
          context: Bheru-Sandbox
          filters:
            branches:
              only: /^feature.*/
 